apiVersion: v1
kind: Service
metadata:
  name: mario-service
  namespace: super-mario
spec:
  type: LoadBalancer
  selector:
    app: mario
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80